set(SPREADSHEETENGINE_STANDALONE_SMOKE_SOURCES
    "${SPREADSHEETENGINE_ROOT}/tests/unit/smoke_main.cxx"
)

set(SPREADSHEETENGINE_STANDALONE_COMPILER_TEST_SOURCES
    "${SPREADSHEETENGINE_ROOT}/tests/unit/compiler_api_tests.cxx"
)

set(SPREADSHEETENGINE_STANDALONE_TOKEN_COMPILER_HOST_TEST_SOURCES
    "${SPREADSHEETENGINE_ROOT}/tests/unit/token_compiler_host_tests.cxx"
)

set(SPREADSHEETENGINE_STANDALONE_MATRIX_TEST_SOURCES
    "${SPREADSHEETENGINE_ROOT}/tests/unit/matrix_api_tests.cxx"
)

set(SPREADSHEETENGINE_STANDALONE_MATH_TEST_SOURCES
    "${SPREADSHEETENGINE_ROOT}/tests/unit/math_api_tests.cxx"
)

set(SPREADSHEETENGINE_STANDALONE_CALENDAR_TEST_SOURCES
    "${SPREADSHEETENGINE_ROOT}/tests/unit/calendar_api_tests.cxx"
)

set(SPREADSHEETENGINE_STANDALONE_TEXT_TEST_SOURCES
    "${SPREADSHEETENGINE_ROOT}/tests/unit/text_api_tests.cxx"
)

set(SPREADSHEETENGINE_STANDALONE_CONFIG_TEST_SOURCES
    "${SPREADSHEETENGINE_ROOT}/tests/unit/config_api_tests.cxx"
)

set(SPREADSHEETENGINE_STANDALONE_EXECUTION_TEST_SOURCES
    "${SPREADSHEETENGINE_ROOT}/tests/unit/execution_api_tests.cxx"
)

set(SPREADSHEETENGINE_STANDALONE_HOST_TEST_SOURCES
    "${SPREADSHEETENGINE_ROOT}/tests/unit/host_api_tests.cxx"
)

set(SPREADSHEETENGINE_STANDALONE_LOGIC_TEST_SOURCES
    "${SPREADSHEETENGINE_ROOT}/tests/unit/logic_api_tests.cxx"
)

set(SPREADSHEETENGINE_STANDALONE_PARSING_TEST_SOURCES
    "${SPREADSHEETENGINE_ROOT}/tests/unit/parsing_api_tests.cxx"
)

set(SPREADSHEETENGINE_STANDALONE_LOOKUP_TEST_SOURCES
    "${SPREADSHEETENGINE_ROOT}/tests/unit/lookup_api_tests.cxx"
)

set(SPREADSHEETENGINE_STANDALONE_ARRAY_TEST_SOURCES
    "${SPREADSHEETENGINE_ROOT}/tests/unit/array_api_tests.cxx"
)

set(SPREADSHEETENGINE_STANDALONE_REFERENCE_TEST_SOURCES
    "${SPREADSHEETENGINE_ROOT}/tests/unit/reference_api_tests.cxx"
)

set(SPREADSHEETENGINE_STANDALONE_CARRIER_TEST_SOURCES
    "${SPREADSHEETENGINE_ROOT}/tests/unit/carrier_api_tests.cxx"
)

set(SPREADSHEETENGINE_STANDALONE_QUERY_TEST_SOURCES
    "${SPREADSHEETENGINE_ROOT}/tests/unit/query_api_tests.cxx"
)

set(SPREADSHEETENGINE_STANDALONE_SHAREDFORMULA_TEST_SOURCES
    "${SPREADSHEETENGINE_ROOT}/tests/unit/sharedformula_api_tests.cxx"
)

set(SPREADSHEETENGINE_STANDALONE_FORMULACELL_TEST_SOURCES
    "${SPREADSHEETENGINE_ROOT}/tests/unit/formulacell_api_tests.cxx"
)

set(SPREADSHEETENGINE_STANDALONE_FODS_TEST_SOURCES
    "${SPREADSHEETENGINE_ROOT}/tests/unit/fods_loader_tests.cxx"
)

set(SPREADSHEETENGINE_STANDALONE_FODS_PARSER_TEST_SOURCES
    "${SPREADSHEETENGINE_ROOT}/tests/unit/fods_formula_parser_tests.cxx"
)

set(SPREADSHEETENGINE_STANDALONE_FODS_EVALUATOR_TEST_SOURCES
    "${SPREADSHEETENGINE_ROOT}/tests/unit/fods_evaluator_tests.cxx"
)

set(SPREADSHEETENGINE_STANDALONE_FODS_REPLAY_TEST_SOURCES
    "${SPREADSHEETENGINE_ROOT}/tests/unit/fods_replay_tests.cxx"
)

set(SPREADSHEETENGINE_STANDALONE_WORKBOOK_FACADE_TEST_SOURCES
    "${SPREADSHEETENGINE_ROOT}/tests/unit/workbook_facade_tests.cxx"
)

set(SPREADSHEETENGINE_STANDALONE_DEPENDENCY_INVALIDATION_TEST_SOURCES
    "${SPREADSHEETENGINE_ROOT}/tests/unit/dependency_invalidation_tests.cxx"
)

set(SPREADSHEETENGINE_STANDALONE_RECALC_PLANNER_TEST_SOURCES
    "${SPREADSHEETENGINE_ROOT}/tests/unit/recalc_planner_tests.cxx"
)

set(SPREADSHEETENGINE_STANDALONE_COMPUTATIONAL_SUBSTRATE_TEST_SOURCES
    "${SPREADSHEETENGINE_ROOT}/tests/unit/computational_substrate_tests.cxx"
)

set(SPREADSHEETENGINE_STANDALONE_COMPUTATIONAL_GRAPH_TEST_SOURCES
    "${SPREADSHEETENGINE_ROOT}/tests/unit/computational_graph_tests.cxx"
)
